services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/yourusername/n8n-render-template
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "pryshvitsyn"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Sos051221*"
      - key: WEBHOOK_TUNNEL_URL
        value: https://delsole.onrender.com
    
